name: Build main on Schedule

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 6 * * 1

permissions:
  id-token: write
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [darwin, linux]
        arch: [amd64, arm64]
        fips: [false, true]
    uses: ./.github/workflows/build.yaml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      fips: ${{ matrix.fips }}
      version: "main"
  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - run: |
          mkdir out
          for dir in envoy*; do
            IFS=- read -r envoy os arch <<< "${dir}"
            for bin in "${dir}"/*; do
              chmod +x "${bin}"

              bin="$(basename "${bin}")"
              IFS=- read -r envoy suffix <<< "${bin}"
              # We know the suffix begins with a version number
              archive_name="envoy-${os}-${arch}-${suffix}"

              # move file into tar.gz and rename to 'envoy' in archive
              tar -C "${dir}" "--transform=flags=r;s|${bin}|envoy|" -czvf "out/${archive_name}.tar.gz" "${bin}"
            done
          done
