name: Build and release (GitHub runners)
run-name: "Build ${{ !inputs.skip-release && 'and release ' || '' }}v${{ inputs.version }}${{ inputs.suffix }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: Envoy version to build (without leading v)
        type: string
        required: true
      suffix:
        description: Additional suffix for release/tag (must include leading '-' if desired)
        type: string
      skip-release:
        description: Skip the release?
        type: boolean
        required: false

permissions:
  contents: write

jobs:
  check-input:
    runs-on: ubuntu-24.04
    steps:
      - name: Fail if version starts with "v"
        env:
          VERSION: ${{ inputs.version }}
        run: |
          if [[ $VERSION == v* ]]; then
            echo "Run this action without 'v' prefix - ${VERSION:1}"
            exit 1
          fi
        shell: bash

  build:
    needs: check-input
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: linux,  arch: amd64, fips: false }
          - { os: linux,  arch: amd64, fips: true  }
          - { os: linux,  arch: arm64, fips: false }
          - { os: darwin, arch: amd64, fips: false }
          - { os: darwin, arch: arm64, fips: false }
    uses: ./.github/workflows/build-github.yaml
    with:
      version: ${{ inputs.version }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      fips: ${{ matrix.fips }}

  package:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      - run: |
          mkdir out
          for dir in envoy*; do
            IFS=- read -r envoy os arch version fips <<< "${dir}"
            for bin in "${dir}"/*; do
              chmod +x "${bin}"

              bin="$(basename "${bin}")"
              archive_name="envoy-${os}-${arch}-v${version}${{ inputs.suffix }}"
              if [[ "${fips}" == "true" ]]; then
                archive_name="${archive_name}+fips"
              fi

              tar -C "${dir}" "--transform=flags=r;s|${bin}|envoy|" -czvf "out/${archive_name}.tar.gz" "${bin}"
            done
          done
      - name: Release
        if: ${{ !inputs.skip-release }}
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          tag_name: v${{ inputs.version }}${{ inputs.suffix }}
          draft: true
          files: |
            out/*
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: envoy-v${{ inputs.version }}${{ inputs.suffix }}
          path: out/
          if-no-files-found: error
